[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

  [[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
remote_images = [
  "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:https:\\/\\/api\\.dublab\\.cat(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http:\\/\\/109\\.69\\.8\\.21(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/api\\.dublab\\.cat(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http:\\/\\/109\\.69\\.8\\.21(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.production.headers]]
    for = "/_next/static/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=86400, immutable"

  [context.main]

    [context.main.images]
    remote_images = [
      "^(?:https:\\/(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/api\\.dublab\\.cat(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http:\\/\\/109\\.69\\.8\\.21(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.main.headers]]
    for = "/_next/static/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=86400, immutable"