import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RadioPlayer from "./components/RadioPlayer";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dublab BCN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RadioPlayer />
        <Header />
        {children}
      </body>
    </html>
  );
}
